### ISSUE TITLE
context.GetSimUe - fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by yoursunny** [omec-project/gnbsim#130]
I have a sighting of a crash in `simue/context` package when a large number of profiles are starting/running in parallel.
This error only occurred once and does not reproduce reliably.
Nevertheless, I'm reporting it here so that this race condition can be reviewed.

## Configuration

<details><summary>1 gNB, 40 UEs, 40 profiles running in parallel</summary>

```yaml
---
info:
  version: 1.0.0
  description: GNBSIM initial local configuration
configuration:
  runConfigProfilesAtStart: true
  singleInterface: false #default value
  execInParallel: true #run all profiles in parallel
  httpServer: # Serves APIs to create/control profiles on the go
    enable: true
    ipAddr: 172.25.192.50
    port: 8080
  gnbs:
    gnb0:
      defaultAmf:
        hostName: 172.25.199.44
        ipAddr: 172.25.199.44
        port: 38412
      globalRanId:
        gNbId:
          bitLength: 24
          gNBValue: "000000"
        plmnId: &ref_0
          mcc: "001"
          mnc: "01"
      n2IpAddr: 172.25.199.50
      n2Port: 9487
      n3IpAddr: 172.25.195.50
      n3Port: 2152
      name: gnb0
      supportedTaList:
        - broadcastPlmnList:
            - plmnId: *ref_0
              taiSliceSupportList:
                - sd: "000000"
                  sst: 128
                - sd: "000000"
                  sst: 129
                - sd: "000000"
                  sst: 130
                - sd: "000000"
                  sst: 131
                - sd: "000000"
                  sst: 132
                - sd: "000000"
                  sst: 133
                - sd: "000000"
                  sst: 134
                - sd: "000000"
                  sst: 135
                - sd: "000000"
                  sst: 136
                - sd: "000000"
                  sst: 137
                - sd: "000000"
                  sst: 138
                - sd: "000000"
                  sst: 139
                - sd: "000000"
                  sst: 140
                - sd: "000000"
                  sst: 141
                - sd: "000000"
                  sst: 142
                - sd: "000000"
                  sst: 143
                - sd: "000000"
                  sst: 144
                - sd: "000000"
                  sst: 145
                - sd: "000000"
                  sst: 146
                - sd: "000000"
                  sst: 147
                - sd: "000000"
                  sst: 148
                - sd: "000000"
                  sst: 149
                - sd: "000000"
                  sst: 150
                - sd: "000000"
                  sst: 151
                - sd: "000000"
                  sst: 152
                - sd: "000000"
                  sst: 153
                - sd: "000000"
                  sst: 154
                - sd: "000000"
                  sst: 155
                - sd: "000000"
                  sst: 156
                - sd: "000000"
                  sst: 157
                - sd: "000000"
                  sst: 158
                - sd: "000000"
                  sst: 159
                - sd: "000000"
                  sst: 160
                - sd: "000000"
                  sst: 161
                - sd: "000000"
                  sst: 162
                - sd: "000000"
                  sst: 163
                - sd: "000000"
                  sst: 164
                - sd: "000000"
                  sst: 165
                - sd: "000000"
                  sst: 166
                - sd: "000000"
                  sst: 167
          tac: "000005"
  profiles:
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n00
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551000
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 128
      sequenceNumber: "000000000020"
      startImsi: "001017005551000"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n01
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551001
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 129
      sequenceNumber: "000000000020"
      startImsi: "001017005551001"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n02
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551002
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 130
      sequenceNumber: "000000000020"
      startImsi: "001017005551002"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n03
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551003
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 131
      sequenceNumber: "000000000020"
      startImsi: "001017005551003"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n04
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551004
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 132
      sequenceNumber: "000000000020"
      startImsi: "001017005551004"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n05
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551005
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 133
      sequenceNumber: "000000000020"
      startImsi: "001017005551005"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n06
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551006
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 134
      sequenceNumber: "000000000020"
      startImsi: "001017005551006"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n07
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551007
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 135
      sequenceNumber: "000000000020"
      startImsi: "001017005551007"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n08
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551008
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 136
      sequenceNumber: "000000000020"
      startImsi: "001017005551008"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n09
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551009
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 137
      sequenceNumber: "000000000020"
      startImsi: "001017005551009"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n10
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551010
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 138
      sequenceNumber: "000000000020"
      startImsi: "001017005551010"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n11
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551011
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 139
      sequenceNumber: "000000000020"
      startImsi: "001017005551011"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n12
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551012
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 140
      sequenceNumber: "000000000020"
      startImsi: "001017005551012"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n13
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551013
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 141
      sequenceNumber: "000000000020"
      startImsi: "001017005551013"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n14
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551014
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 142
      sequenceNumber: "000000000020"
      startImsi: "001017005551014"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n15
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551015
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 143
      sequenceNumber: "000000000020"
      startImsi: "001017005551015"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n16
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551016
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 144
      sequenceNumber: "000000000020"
      startImsi: "001017005551016"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n17
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551017
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 145
      sequenceNumber: "000000000020"
      startImsi: "001017005551017"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n18
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551018
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 146
      sequenceNumber: "000000000020"
      startImsi: "001017005551018"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n19
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551019
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 147
      sequenceNumber: "000000000020"
      startImsi: "001017005551019"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n20
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551020
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 148
      sequenceNumber: "000000000020"
      startImsi: "001017005551020"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n21
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551021
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 149
      sequenceNumber: "000000000020"
      startImsi: "001017005551021"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n22
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551022
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 150
      sequenceNumber: "000000000020"
      startImsi: "001017005551022"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n23
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551023
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 151
      sequenceNumber: "000000000020"
      startImsi: "001017005551023"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n24
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551024
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 152
      sequenceNumber: "000000000020"
      startImsi: "001017005551024"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n25
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551025
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 153
      sequenceNumber: "000000000020"
      startImsi: "001017005551025"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n26
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551026
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 154
      sequenceNumber: "000000000020"
      startImsi: "001017005551026"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n27
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551027
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 155
      sequenceNumber: "000000000020"
      startImsi: "001017005551027"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n28
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551028
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 156
      sequenceNumber: "000000000020"
      startImsi: "001017005551028"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n29
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551029
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 157
      sequenceNumber: "000000000020"
      startImsi: "001017005551029"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n30
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551030
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 158
      sequenceNumber: "000000000020"
      startImsi: "001017005551030"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n31
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551031
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 159
      sequenceNumber: "000000000020"
      startImsi: "001017005551031"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n32
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551032
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 160
      sequenceNumber: "000000000020"
      startImsi: "001017005551032"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n33
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551033
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 161
      sequenceNumber: "000000000020"
      startImsi: "001017005551033"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n34
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551034
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 162
      sequenceNumber: "000000000020"
      startImsi: "001017005551034"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n35
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551035
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 163
      sequenceNumber: "000000000020"
      startImsi: "001017005551035"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n36
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551036
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 164
      sequenceNumber: "000000000020"
      startImsi: "001017005551036"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n37
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551037
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 165
      sequenceNumber: "000000000020"
      startImsi: "001017005551037"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n38
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551038
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 166
      sequenceNumber: "000000000020"
      startImsi: "001017005551038"
      ueCount: 1
    - dataPktCount: 5
      defaultAs: 172.25.193.42
      dnn: n39
      enable: true
      execInParallel: true
      gnbName: gnb0
      key: c5dabfd66406eeb9871f18eacf1f8864
      opc: efb1b89d8759b701a681875d09e322eb
      plmnId:
        mcc: "001"
        mnc: "01"
      profileName: deregister-001017005551039
      profileType: deregister
      sNssai:
        sd: "000000"
        sst: 167
      sequenceNumber: "000000000020"
      startImsi: "001017005551039"
      ueCount: 1
logger:
  logLevel: info # how detailed the log will be, values: trace, debug, info, warn, error, fatal, panic
```

</details>
